### ISSUE TITLE
Error in line 60: 'submission' is not defined

### ISSUE THREAD

**Issue by wayfarren** [greembow/google_classroom_assignment_list#6] opened 2022-02-14 05:59 UTC
Traceback (most recent call last):
  File "/<working-directory>/google_classroom_assignment_list/src/main.py", line 60, in <module>
    submission
NameError: name 'submission' is not defined

**Comment by Frigyes06** [comment] 2022-02-14 06:12
PR #5 addresses this. It can be closed

**Comment by greembow** [comment] 2022-02-14 06:16
Duplicate of #5 . closed

**Closed as completed by greembow** 2022-02-14 06:16 UTC
